### Find All content
GET http://localhost:8080/api/content
### Get Content By ID
GET http://localhost:8080/api/content/1

### Create New Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
     "id": 2,
    "title": "my fourh plog post",
    "desc": "my fourth plog Post",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2023-08-17T22:31:19.5864701",
    "dateUpdated": null,
    "url": ""
    }
###update conetent
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "",
  "desc": "my first Blog POst!!!",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-18T19:20:33.1216318",
  "dateUpdated": null,
  "url": "zero.pp"
}

###delete conetent
DELETE http://localhost:8080/api/content/1
